# Generated by Django 5.2.4 on 2025-07-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hsn', models.CharField(max_length=13)),
                ('gst', models.IntegerField(max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
    ]
