# Generated by Django 5.2.4 on 2025-07-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biller', '0002_product_pieces_in_packets'),
    ]

    operations = [
        migrations.CreateModel(
            name='addProduct',
            fields=[
                ('customerid', models.CharField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=100)),
                ('gstno', models.CharField(blank=True, max_length=20, null=True)),
                ('customeraddress', models.CharField(max_length=200)),
                ('customerstate', models.CharField(max_length=100)),
                ('customertype', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=10)),
            ],
        ),
    ]
