# Generated by Django 5.2.4 on 2025-07-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biller', '0003_addproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addProduct',
            new_name='addCustomer',
        ),
    ]
