# Generated by Django 5.2.4 on 2025-07-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biller', '0004_rename_addproduct_addcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='productloggin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hsn', models.CharField(max_length=13)),
                ('gst', models.IntegerField(max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=10)),
                ('pieces_in_packets', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
