# Generated by Django 5.2.4 on 2025-07-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biller', '0005_productloggin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productloggin',
            name='gst',
            field=models.IntegerField(),
        ),
    ]
