# Generated by Django 5.2.4 on 2025-07-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biller', '0006_alter_product_gst_alter_productloggin_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='productloggin',
            name='eacch_piece_in_packets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
