# Generated by Django 5.2.4 on 2025-07-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biller', '0007_productloggin_eacch_piece_in_packets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productloggin',
            old_name='eacch_piece_in_packets',
            new_name='each_piece_in_packets',
        ),
    ]
