# Generated by Django 5.2.4 on 2025-07-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biller', '0008_rename_eacch_piece_in_packets_productloggin_each_piece_in_packets'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='each_piece_in_packets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
